version: '3'

services: 
  prestashop:
    container_name: be-adidas
    image: jacoblink/be-prestashop:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mariadb

  mariadb:
    container_name: adidas-db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
     - ./mariadb:/docker-entrypoint-initdb.d
      